
#ifndef _SATA_XGENE_SERDES_CSR_H_
#define _SATA_XGENE_SERDES_CSR_H_

#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_LSB		4
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_MSB		21
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_WIDTH		18
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_MASK		0x003ffff0
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_SHIFT_MASK		0x4
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_RD(src)	((FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_MASK & (uint32_t)(src)) >> FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_SHIFT_MASK)
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_WR(dst)	(FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_MASK & ((uint32_t)(dst) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_SHIFT_MASK))
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_SET(dst, src)	(((dst) & ~FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_MASK) | (((uint32_t)(src) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_SHIFT_MASK) & FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_ADDR_MASK))

#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_LSB		0
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_MSB		0
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_WIDTH		1
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_MASK		0x00000001
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_SHIFT_MASK		0x0
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_RD(src)	((FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_MASK & (uint32_t)(src)))
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_WR(dst)	(FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_MASK & ((uint32_t)(dst) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_SHIFT_MASK))
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_SET(dst, src)	(((dst) & ~FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_MASK) | (((uint32_t)(src) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_SHIFT_MASK) & FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_WR_CMD_MASK))

#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_LSB		2
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_MSB		2
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_WIDTH		1
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_MASK		0x00000004
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_SHIFT_MASK		0x2
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_RD(src)	((FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_MASK & (uint32_t)(src)) >> FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_SHIFT_MASK)
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_WR(dst)	(FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_MASK & ((uint32_t)(dst) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_SHIFT_MASK))
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_SET(dst, src)	(((dst) & ~FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_MASK) | (((uint32_t)(src) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_SHIFT_MASK) & FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_CMD_DONE_MASK))

#define SM_PCIE_X8_SDS_CSR_REGS_PCIE_SDS_IND_WDATA_REG__ADDR 0xa01c
#define SM_PCIE_X8_SDS_CSR_REGS_PCIE_SDS_IND_CMD_REG__ADDR 0xa014
#define SM_PCIE_X8_SDS_CSR_REGS_PCIE_SDS_IND_RDATA_REG__ADDR 0xa018

#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_LSB		1
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_MSB		1
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_WIDTH		1
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_MASK		0x00000002
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_SHIFT_MASK		0x1
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_RD(src)	((FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_MASK & (uint32_t)(src)) >> FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_SHIFT_MASK)
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_WR(dst)	(FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_MASK & ((uint32_t)(dst) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_SHIFT_MASK))
#define FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_SET(dst, src)	(((dst) & ~FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_MASK) | (((uint32_t)(src) << FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_SHIFT_MASK) & FIELD_PCIE_SDS_IND_CMD_REG_CFG_IND_RD_CMD_MASK))

#define SM_PCIE_CLKRST_CSR_PCIE_SRST__ADDR                 0xc000
#define SM_PCIE_CLKRST_CSR_PCIE_CLKEN__ADDR                0xc008
#define SM_PCIE_X8_SDS_CSR_REGS_PCIE_CLK_MACRO_REG__ADDR   0xa094

#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_LSB		0
#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_MSB		0
#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_WIDTH		1
#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_MASK		0x00000001
#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_SHIFT_MASK		0x0
#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_RD(src)	((FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_MASK & (uint32_t)(src)))
#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_WR(dst)	(FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_MASK & ((uint32_t)(dst) << FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_SHIFT_MASK))
#define FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_SET(dst, src)	(((dst) & ~FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_MASK) | (((uint32_t)(src) << FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_SHIFT_MASK) & FIELD_PCIE_CLK_MACRO_REG_I_RESET_B_MASK))

#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_LSB		21
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_MSB		22
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_WIDTH		2
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_MASK		0x00600000
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_SHIFT_MASK		0x15
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_RD(src)	((FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_MASK & (uint32_t)(src)) >> FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_SHIFT_MASK)
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_WR(dst)	(FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_MASK & ((uint32_t)(dst) << FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_SHIFT_MASK))
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_SET(dst, src)	(((dst) & ~FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_MASK) | (((uint32_t)(src) << FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_SHIFT_MASK) & FIELD_PCIE_CLK_MACRO_REG_I_PLL_REFDIV_MASK))

#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_LSB		7
#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_MSB		11
#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_WIDTH		5
#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_MASK		0x00000f80
#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_SHIFT_MASK		0x7
#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_RD(src)	((FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_MASK & (uint32_t)(src)) >> FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_SHIFT_MASK)
#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_WR(dst)	(FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_MASK & ((uint32_t)(dst) << FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_SHIFT_MASK))
#define FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_SET(dst, src)	(((dst) & ~FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_MASK) | (((uint32_t)(src) << FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_SHIFT_MASK) & FIELD_PCIE_CLK_MACRO_REG_I_CUSTOMEROV_MASK))

#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_LSB		30
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_MSB		30
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_WIDTH		1
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_MASK		0x40000000
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_SHIFT_MASK		0x1e
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_RD(src)	((FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_MASK & (uint32_t)(src)) >> FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_SHIFT_MASK)
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_WR(dst)	(FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_MASK & ((uint32_t)(dst) << FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_SHIFT_MASK))
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_SET(dst, src)	(((dst) & ~FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_MASK) | (((uint32_t)(src) << FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_SHIFT_MASK) & FIELD_PCIE_CLK_MACRO_REG_O_PLL_LOCK_MASK))

#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_LSB		31
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_MSB		31
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_WIDTH		1
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_MASK		0x80000000
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_SHIFT_MASK		0x1f
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_RD(src)	((FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_MASK & (uint32_t)(src)) >> FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_SHIFT_MASK)
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_WR(dst)	(FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_MASK & ((uint32_t)(dst) << FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_SHIFT_MASK))
#define FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_SET(dst, src)	(((dst) & ~FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_MASK) | (((uint32_t)(src) << FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_SHIFT_MASK) & FIELD_PCIE_CLK_MACRO_REG_O_PLL_READY_MASK))
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_LSB		12
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_MSB		20
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_WIDTH		9
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_MASK		0x001ff000
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_SHIFT_MASK		0xc
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_RD(src)	((FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_MASK & (uint32_t)(src)) >> FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_SHIFT_MASK)
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_WR(dst)	(FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_MASK & ((uint32_t)(dst) << FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_SHIFT_MASK))
#define FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_SET(dst, src)	(((dst) & ~FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_MASK) | (((uint32_t)(src) << FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_SHIFT_MASK) & FIELD_PCIE_CLK_MACRO_REG_I_PLL_FBDIV_MASK))

#endif






